import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Employee.java
 *
 * This is our OOP "model" class. It represents a single row of the
 * "employees" table as a Java object, nothing more.
 *
 * Why a separate class instead of passing raw values around?
 *  - Encapsulation: fields are private, accessed only through
 *    getters/setters, so other classes can't corrupt the data directly.
 *  - Readability: passing one "Employee" object is much clearer than
 *    passing 5 separate parameters (name, email, department, ...) around.
 *  - Reusability: EmployeeDAO, Main, and any future class (e.g. a
 *    report generator) can all reuse this same class.
 */
public class Employee {

    // Fields are private -> this is encapsulation, a core OOP concept.
    private int id;                 // primary key, auto-generated by the DB
    private String name;
    private String email;
    private String department;
    private BigDecimal salary;      // BigDecimal is used (not double) because
                                     // money values must never lose precision
    private LocalDate joiningDate;

    /**
     * Full constructor - used when we already know the DB-generated id
     * (e.g. when reading a row back from the database).
     */
    public Employee(int id, String name, String email, String department,
                     BigDecimal salary, LocalDate joiningDate) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.department = department;
        this.salary = salary;
        this.joiningDate = joiningDate;
    }

    /**
     * Constructor without id - used when creating a brand-new employee
     * that hasn't been inserted into the database yet (the DB will
     * generate the id for us via SERIAL/AUTO_INCREMENT).
     */
    public Employee(String name, String email, String department,
                     BigDecimal salary, LocalDate joiningDate) {
        this(0, name, email, department, salary, joiningDate);
    }

    // ---------- Getters and setters ----------
    // These are the only way outside classes can read/modify our
    // private fields. This keeps validation/control in one place.

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public LocalDate getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(LocalDate joiningDate) {
        this.joiningDate = joiningDate;
    }

    /**
     * Overriding toString() so that printing an Employee object in the
     * console (System.out.println(employee)) gives a readable line
     * instead of the default "Employee@1a2b3c" hash output.
     */
    @Override
    public String toString() {
        return String.format(
                "ID: %-4d | Name: %-20s | Email: %-25s | Dept: %-12s | Salary: %-10s | Joined: %s",
                id, name, email, department, salary, joiningDate
        );
    }
}
